### ISSUE TITLE
Older version: 10.00.19041.0928

### ISSUE THREAD

**Issue by foolydooly** [naxl/directx12offline#1]
According to https://en.wikipedia.org/wiki/DirectX#Version_history

**12.2**
**10.00.19041.0928** | November 10, 2020 | Windows 10, Ultimate
**10.00.22000.1000** | October 5, 2021 | Windows 11, Added native refresh rate switching and improved graphics capabilities to Windows Subsystem for Linux

One we have listed here is "**10.00.19041.0928**". Is it possible to get this updated to 10.00.22000.1000?

**Comment by naxl** [comment]
I believe they haven't made it available via an offline installer, and I'm afraid they don't have any intentions to. 

This link will take you to the details.aspx page of the [Microsoft download center](https://www.microsoft.com/en-in/download/details.aspx?id=8109).

The most recent extract available on their official documentation page/download corner is dated **20th Feb 2021**. The update in question was released on **October 5th, 2021**, and it is evident that it is only available through the online installer. You can try websetup or install the most recent DirectX SDK (offline) to obtain the **10.00.22000.1000**.
